---
version: 2
updates:
  - package-ecosystem: "gomod"
    directory: /
    groups:
      all:
        patterns:
          - "*"
    open-pull-requests-limit: 10
    schedule:
      interval: "weekly"

  - package-ecosystem: "github-actions"
    directory: /
    groups:
      all:
        patterns:
          - "*"
    open-pull-requests-limit: 10
    schedule:
      interval: "weekly"
