---
extends: default

rules:
  # 200 chars should be enough, but don't fail if a line is longer
  line-length:
    max: 200
    level: warning

  truthy:
    # GHA keywork `on` triggers truthy warning
    # see: https://github.com/adrienverge/yamllint/issues/430
    ignore: |
      .github/workflows/*
